name: Cleanup Untagged Images

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # Run every Sunday at midnight

permissions:
  packages: write

jobs:
  delete-untagged-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Delete untagged images for Server
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'jellyfin-rffmpeg-swarm-server'
          package-type: 'container'
          min-versions-to-keep: 2
          delete-only-untagged-versions: 'true'

      - name: Delete untagged images for Worker
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'jellyfin-rffmpeg-swarm-worker'
          package-type: 'container'
          min-versions-to-keep: 2
          delete-only-untagged-versions: 'true'
